language: go

go_import_path: github.com/ramonmedeiros/state_machine_go/

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
